export const dataUser = [
  {
    _id: "63701cc1f03239b7f700000e",
    fullName: "Shelly",
    email: "swelb12@gmail.com",
    password: "abc12346",
    phone: "7036619983",
    token:
      "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.GuoUe6tw79bJlbU1HU0ADX0pr0u2kf3r_4OdrDufSfQ",
    role: "admin",
    loginType: "normal",
    avatar: "",
  },
  {
    _id: "63701cc1f03239b7f744440e",
    fullName: "mai slyly",
    email: "maingungok@gmail.com",
    password: "abc12346",
    phone: "038598347",
    token: "123456",
    role: "user",
    loginType: "normal",
    avatar: "",
  },
];
export const dataTour = [
  {
    category: "tourEco",
    title: "Tham hiem da lat",
    departure: "Hà Nội",
    destination: "Đà lạt",
    numberDay: 4,
    price: 23455,
    content: "Choi het minh ve la vui",
    images: "123hjds",
    thumbnail: "123",
    codeTour: "DHN",
    description: "",
  },
  {
    category: "tourEco",
    title: "Tham hiem da lat",
    departure: "Hà Nội",
    destination: "Đà lạt",
    numberDay: 4,
    price: 23455,
    content: "Choi het minh ve la vui",
    images: "123hjds",
    thumbnail: "123",
    codeTour: "DTHN",
    description: "",
  },
  {
    category: "tourEco",
    title: "Tham hiem da lat",
    departure: "Hà Nội",
    destination: "Đà lạt",
    numberDay: 4,
    price: 23455,
    content: "Choi het minh ve la vui",
    images: "123hjds",
    thumbnail: "123",
    codeTour: "DTHA",
    description: "",
  },
  {
    category: "tourEco",
    title: " da lat",
    departure: "Hà Nội",
    destination: "Đà lạt",
    numberDay: 4,
    price: 23455,
    content: "Choi het minh ve la vui",
    images: "123hjds",
    thumbnail: "123",
    codeTour: "TAHN",
    description: "",
  },
  {
    category: "tourEco",
    title: "Tham hiem ",
    departure: "Hà Nội",
    destination: "Đà lạt",
    numberDay: 4,
    price: 23455,
    content: "Choi het minh ve la vui",
    images: "123hjds",
    thumbnail: "123",
    codeTour: "DTNF",
    description: "",
  },
];
export const dataProvince = [
  { title: "An Giang" },
  { title: "Bà Rịa – Vũng Tàu" },
  { title: "Bạc Liêu" },
  { title: "Bắc Giang" },
  { title: "Bắc Kạn" },
  { title: "Bắc Ninh" },
  { title: "Bến Tre" },
  { title: "Bình Dương" },
  { title: "Bình Định" },
  { title: "Bình Phước" },
  { title: "Bình Thuận" },
  { title: "Cà Mau" },
  { title: "Cao Bằng" },
  { title: "Cần Thơ" },
  { title: "Đà Nẵng" },
  { title: "Đắk Lắk" },
  { title: "Đắk Nông" },
  { title: "Điện Biên" },
  { title: "Đồng Nai" },
  { title: "Đồng Tháp" },
  { title: "Gia Lai" },
  { title: "Hà Giang" },
  { title: "Hà Nam" },
  { title: "Hà Nội" },
  { title: "Hà Tĩnh" },
  { title: "Hải Dương" },
  { title: "Hải Phòng}" },
  { title: "Hậu Giang" },
  { title: "Hòa Bình" },
  { title: "Thành phố Hồ Chí Minh" },
  { title: "Hưng Yên" },
  { title: "Khánh Hòa" },
  { title: "Kiên Giang" },
  { title: "Kon Tum" },
  { title: "Lai Châu" },
  { title: "Lạng Sơn" },
  { title: "Lào Cai" },
  { title: "Lâm Đồng" },
  { title: "Long An" },
  { title: "Nam Định" },
  { title: "Nghệ An" },
  { title: "Ninh Bình" },
  { title: "Ninh Thuận" },
  { title: "Phú Thọ" },
  { title: "Phú Yên" },
  { title: "Quảng Bình" },
  { title: "Quảng Nam" },
  { title: "Quảng Ngãi" },
  { title: "Quảng Ninh" },
  { title: "Quảng Trị" },
  { title: "Sóc Trăng" },
  { title: "Sơn La" },
  { title: "Tây Ninh" },
  { title: "Thái Bình" },
  { title: "Thái Nguyên" },
  { title: "Thanh Hóa" },
  { title: "Thừa Thiên Huế" },
  { title: "Tiền Giang" },
  { title: "Trà Vinh" },
  { title: "Tuyên Quang" },
  { title: "Vĩnh Long" },
  { title: "Vĩnh Phúc" },
  { title: "Yên Bái" },
];
export const dataOrder = [
  {
    idTour:"",
    idCustomer:"",
    name:"",
    phone:"",
    date:"",
    email:"",
    totalPerson:3,
    totalMoney:3000,
  }
]
